### ISSUE TITLE
Build fails due to lack of `Suspense` on `useSearchParams`

### ISSUE THREAD

**Issue by calejvaldez** [ojosproject/iris#36]
### Summary

Attempting to build fails due to the lack of `Suspense`. The logs suggested to [due this article](https://nextjs.org/docs/messages/missing-suspense-with-csr-bailout).

### What is the expected correct behavior?

Build successfully.

### Steps to reproduce

Run `cargo tauri build` on `main`.

### Relevant logs and/or screenshots

Logs from NextJS after running `cargo tauri build`:

```plaintext
    Running beforeBuildCommand `npm run build`

> iris@0.0.0 build
> next build

  ▲ Next.js 14.2.5

   Creating an optimized production build ...
 ✓ Compiled successfully
 ✓ Linting and checking validity of types
 ✓ Collecting page data
   Generating static pages (0/9)  [    ] ⨯ useSearchParams() should be wrapped in a suspense boundary at page "/care_instructions/view". Read more: https://nextjs.org/docs/messages/missing-suspense-with-csr-bailout
    at o (/Users/calejvaldez/git/ojos/iris/.next/server/chunks/738.js:1:10811)
    at s (/Users/calejvaldez/git/ojos/iris/.next/server/chunks/738.js:1:21761)
    at _ (/Users/calejvaldez/git/ojos/iris/.next/server/app/care_instructions/view/page.js:1:2763)
    at nj (/Users/calejvaldez/git/ojos/iris/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:46251)
    at nM (/Users/calejvaldez/git/ojos/iris/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47571)
    at nN (/Users/calejvaldez/git/ojos/iris/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546)
    at nI (/Users/calejvaldez/git/ojos/iris/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47010)
    at nM (/Users/calejvaldez/git/ojos/iris/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47717)
    at nM (/Users/calejvaldez/git/ojos/iris/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:61546)
    at nN (/Users/calejvaldez/git/ojos/iris/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546)

Error occurred prerendering page "/care_instructions/view". Read more: https://nextjs.org/docs/messages/prerender-error

 ✓ Generating static pages (9/9)

> Export encountered errors on following paths:
	/care_instructions/view/page: /care_instructions/view
    Error beforeBuildCommand `npm run build` failed with exit code 1
```

### Operating System

macOS

**Comment by calejvaldez** [comment]
I struggled to figure out *where* the `Suspense` was supposed to go, but I followed the NextJS docs' example of wrapping the entire component inside of a suspense. I do think we should add more things, such as a fallback skeleton.
